apiVersion: v1
kind: Service
metadata:
  name: compair
  labels:
    app: compair
spec:
  ports:
    - port: 80
      targetPort: 3031
  selector:
    app: compair
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-claim
  labels:
    app: compair
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: compair
  labels:
    app: compair
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: compair
        tier: frontend
    spec:
      containers:
      - name: compair-app
        image: ubcctlt/compair-app
        env:
#        - name: DATABASE_URI
#          value: "mysql+pymysql://compair:thisiscompairpassword@compair-mysql:3306/compair"
        - name: DB_HOST
          value: compair-mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_USERNAME
          value: compair
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password.txt
        - name: DB_NAME
          value: compair
        ports:
        - containerPort: 3031
          name: compair-app
        volumeMounts:
        - name: nfs-persistent-storage
          mountPath: /code/persistent
      volumes:
      - name: nfs-persistent-storage
        persistentVolumeClaim:
          claimName: nfs-pv-claim