apiVersion: v1
kind: Service
metadata:
  name: compair-nfs-server
  labels:
    app: compair
spec:
  ports:
    - port: 2049
      name: nfs
    - port: 20048
      name: mountd
    - port: 111
      name: rpcbind
  selector:
    app: compair
    tier: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server-pv-claim
  annotations:
    volume.alpha.kubernetes.io/storage-class: foo
  labels:
    app: compair
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: compair-nfs
  labels:
    app: compair
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: compair
        tier: nfs
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google-samples/nfs-server:1.1
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-storage
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: nfs-server-pv-claim