version: '2'
services:
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=randompassword
      - MYSQL_DATABASE=compair
      - MYSQL_USER=compair
      - MYSQL_PASSWORD=compair
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - "13306:3306"
  app:
    image: ubcctlt/compair-app
    environment:
      - DB_DRIVER=mysql+pymysql
      - DB_USERNAME=compair
      - DB_PASSWORD=compair
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=compair
      - DEV=1
      #- GA_TRACKING_ID=12345
    volumes:
      - .:/code
      - ./.data/persistent:/code/persistent
    depends_on:
      - db
  web:
    image: nginx:1.11
    volumes:
      - ./deploy/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./acj/static:/compair/app:ro
    ports:
      - "8080:80"
    depends_on:
      - app
